### ISSUE TITLE
Style guide

### ISSUE THREAD

**Issue by jamen** [ptp/new#13]
- Always compile LESS -> CSS, don't work on the CSS directly.
- Put all assets (images, javascript, less, css, etc.) in the `assets` folder under their appropriate sub-folder. <sub>[ref](https://github.com/ptp-chat/new/tree/gh-pages/assets)</sub>
- All pages should be at the root `<page>.html` unless there is sub-pages such as `/docs/api/whatever.html`
- LESS / CSS file should be named after the file it associates with, e.g. `index.html` uses `index.less`.  `rules.html` uses `rules.less`.
- All LESS files should import `common.less`. <sub>[ref](https://github.com/ptp-chat/new/blob/gh-pages/assets/styles/rules.less#L3)</sub>

**Comment by jleeto** [comment]
Will review thoroughly soon -- thank you for this brief referral.

**Comment by jamen** [comment]
Updated style guide a bit more, in case we plan on adding new pages in the future.

**Comment by jamen** [comment]
#14 closes.
